2025-06-30 14:19:16.204 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2025-06-30 14:19:16.204 [info] Native locator: Refresh started
2025-06-30 14:19:16.204 [info] Native locator: Refresh started
2025-06-30 14:19:16.204 [info] > pixi --version
2025-06-30 14:19:16.205 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:16.211 [info] > C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe -c "import sys;print(sys.executable)"
2025-06-30 14:19:16.215 [error] [Error: Command failed: C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: C:Usersmarkrish2AppDataLocalProgramsPythonPython313python.exe: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\markrish2\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -c "import sys;print(sys.executable)"'
}
2025-06-30 14:19:16.218 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:16.222 [info] Native locator: Refresh finished in 1332 ms
2025-06-30 14:19:16.506 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:17.506 [warning] Shell integration may not be active, environment activated may be overridden by the shell.
2025-06-30 14:19:17.508 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:17.513 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:17.514 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:17.806 [info] Shell integration status changed, can confirm it's working.
2025-06-30 14:19:17.808 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:17.811 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
2025-06-30 14:19:17.815 [warning] could not find a pixi interpreter for the interpreter at C:\Users\markrish2\AppData\Local\Programs\Python\Python313\python.exe
